# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


replicaCount: 1
image:
  #registry: docker.io
  repository: spolish
  tag: "v1.0.8-04ad298"
  arch: "amd64"
secret:
  name: kbot
  tokenKey: token
  tokenName: 6369096639:AAFC85t4AHcljTwSRvL6B_w8DUUKKSj-kNQ
service:
  port: 80
securityContext:
  privileged: true
