# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: gcr.io
  repository: k8s-k3s-spolish
  tag: "v1.0.6-b63acad"
  arch: amd64

secret:
  name: kbot
  tokenKey: token
  tokenName: TELE_TOKEN

service:
  port: 80

securityContext:
  privileged: true