name: KBOT-CICD

on: push

  
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:                  
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Run test
        run: make test

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
           credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
           project_id: ${{ secrets.GCR_PROJECT }}
      - name: 'gcloud'
        run: gcloud --quiet auth configure-docker

      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY: ${{ secrets.GCR_PROJECT }}
        run: make image push 
